<?php

declare(strict_types=1);

namespace Database\SeedersKb;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * 15 principios iniciales de coaching reutilizables.
 * COMPOSE stage los inyecta en notas_coach, tips[], notas de ejercicio.
 *
 * Distribución MVP:
 *   - 7 entrenamiento
 *   - 4 nutrición
 *   - 1 suplementación
 *   - 3 hábitos
 *
 * Ver docs/wellcore-engine-v2/03-knowledge-base-schema.md §3.4
 * Idempotente por slug.
 */
final class PrinciplesSeeder extends Seeder
{
    public function run(): void
    {
        $now = now()->toDateTimeString();

        $rows = [
            // ─── ENTRENAMIENTO (7) ─────────────────────────────────────────────
            [
                'slug' => 'sobrecarga_progresiva',
                'name' => 'Sobrecarga progresiva',
                'vertical' => 'entrenamiento',
                'description_short' => 'Aumentar progresivamente la demanda (peso, reps, tempo, densidad) para forzar adaptación.',
                'description_long' => "La sobrecarga progresiva es el motor de cualquier ganancia muscular o de fuerza. No basta con entrenar duro — hay que entrenar progresivamente más duro semana a semana.\n\nVariables progresables (en orden de prioridad para hipertrofia): 1) número de series por grupo muscular, 2) reps por serie, 3) carga, 4) tiempo bajo tensión, 5) densidad (reducir descanso).\n\nNo todas las semanas se progresa todo. Lo común es subir 1 variable a la vez y consolidar.",
                'when_to_apply' => 'En todos los planes de entrenamiento. Especialmente importante mencionar en semana 2 cuando el cliente empieza a calibrar y entender que el plan crece con él.',
                'example_usage' => 'Notas del coach semana 2: "Si la semana 1 completaste todas las series con la técnica perfecta, esta semana subí 2.5-5kg en los compuestos. Si te quedaste corto, repetí pesos pero ajustá la técnica primero."',
                'tags' => json_encode(['hipertrofia', 'fuerza', 'fundamental']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'tecnica_primero',
                'name' => 'Técnica antes que carga',
                'vertical' => 'entrenamiento',
                'description_short' => 'Ningún peso vale más que la articulación. Si la técnica se rompe, bajar peso o terminar la serie.',
                'description_long' => "La técnica precede a la carga. Levantar mucho con técnica mala acumula daño articular invisible que aparece años después (hombro, lumbar, rodilla).\n\nReglas operativas: 1) calentamiento específico con barra vacía o pesos muy bajos para repasar patrón, 2) si en una serie de trabajo la última rep pierde rango o forma, NO contar reps adicionales, 3) ante duda de técnica, grabar video y revisar.",
                'when_to_apply' => 'Principiantes siempre. Intermedios cuando empiezan ejercicio nuevo. Avanzados en deload o post-lesión.',
                'example_usage' => 'Notas del coach: "El primer mes no me interesa cuánto cargás. Me interesa que la sentadilla baje hasta romper paralela con la espalda en neutro. El peso viene después."',
                'tags' => json_encode(['fundamental', 'principiante', 'prevencion_lesiones']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'variacion_estimulos',
                'name' => 'Variación de estímulos sin caos',
                'vertical' => 'entrenamiento',
                'description_short' => 'Rotar metodologías (series rectas, drop, superset) cada 4-6 semanas para evitar estancamiento sin perder progresión.',
                'description_long' => "El músculo se adapta al estímulo repetido. Después de 4-6 semanas con la misma metodología, las ganancias se reducen.\n\nVariar NO significa cambiar de plan cada semana. Significa rotar técnicas avanzadas (drop sets, supersets, pirámides) en los ejercicios accesorios, manteniendo los compuestos principales con series rectas y progresión lineal.",
                'when_to_apply' => 'Intermedios+ después de 4 semanas en el mismo bloque. Para principiantes NO aplica — ellos progresan con series rectas largas (3-6 meses).',
                'example_usage' => 'Bloque 2 semana 1: "Esta semana introducimos un drop set al final del press de banca. Es la única técnica avanzada del día — no la metas en los demás ejercicios."',
                'tags' => json_encode(['hipertrofia', 'intermedio', 'avanzado']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'recuperacion_es_entrenamiento',
                'name' => 'La recuperación es parte del entrenamiento',
                'vertical' => 'entrenamiento',
                'description_short' => 'El músculo crece entre sesiones, no durante. Sueño + nutrición + descanso entre series son tan importantes como el ejercicio.',
                'description_long' => "El estímulo de entrenamiento daña fibras musculares. La adaptación (hipertrofia, fuerza) ocurre en la recuperación. Si no se recupera, no se progresa.\n\nFactores de recuperación: 1) sueño 7-9h consistentes, 2) proteína distribuida a lo largo del día, 3) descanso entre series suficiente para mantener carga (90-180s compuestos), 4) descanso entre sesiones del mismo grupo (48-72h).",
                'when_to_apply' => 'Cuando el cliente reporta fatiga acumulada, dolor articular persistente, o pérdida de fuerza inesperada. Recomendar deload antes que insistir.',
                'example_usage' => 'Si el cliente dice "estoy cansado pero quiero entrenar igual": "Te entiendo. Hagamos esto: bajá 30% el volumen hoy. Si mañana te sentís bien, retomamos. Forzar sobre fatiga te lleva a lesión."',
                'tags' => json_encode(['fundamental', 'recuperacion', 'prevencion_lesiones']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'consistencia_sobre_intensidad',
                'name' => 'Consistencia gana a intensidad',
                'vertical' => 'entrenamiento',
                'description_short' => '4 entrenos por semana durante 12 semanas vencen a 7 entrenos perfectos durante 3 semanas + 9 semanas perdidas.',
                'description_long' => "La adaptación muscular y de fuerza requiere ESTÍMULO REPETIDO en el tiempo. Un cliente que entrena 4 días consistentes durante 6 meses obtiene mejores resultados que uno que entrena 6 días extremos durante 3 semanas y se quema.\n\nMejor adaptar el plan a la vida real del cliente que pretender que la vida se adapte al plan ideal.",
                'when_to_apply' => 'En la primera sesión / intake. Cuando un cliente con vida ocupada pide planes muy ambiciosos. Cuando reaparece tras una pausa.',
                'example_usage' => 'En notas_coach iniciales: "El plan está diseñado para 4 días — sostener 4 días durante 12 semanas seguidas vale más que cualquier intento de hacer 6 días los primeros 15 y desaparecer."',
                'tags' => json_encode(['fundamental', 'adherencia', 'realismo']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'deload_planificado',
                'name' => 'Deload planificado cada 4-6 semanas',
                'vertical' => 'entrenamiento',
                'description_short' => 'Semana ligera con -30% volumen y -70% intensidad cada 4-6 semanas previene overtraining y consolida ganancias.',
                'description_long' => "El deload no es debilidad ni vagancia — es necesidad biológica. Cada 4-6 semanas de carga progresiva, una semana de reducción permite que el sistema nervioso, articulaciones y tejido conectivo se actualicen al nuevo nivel.\n\nProtocolo estándar: mantener los ejercicios y la frecuencia, reducir volumen a 60-70% y carga a 70-80% del trabajo. Sensación: salir del gym 'queriendo entrenar más'.",
                'when_to_apply' => 'En todo bloque de 4+ semanas. Especialmente importante mencionarlo en el plan antes de la semana 4 para que el cliente no piense que es regresión.',
                'example_usage' => 'Notas semana 4 (peak): "La próxima semana es DELOAD — vas a entrenar igual, pero con menos peso y menos series. No es vagancia, es ciencia. Salí del gym con energía. Después arrancamos bloque nuevo."',
                'tags' => json_encode(['intermedio', 'avanzado', 'recuperacion']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'carga_progresiva_post_lesion',
                'name' => 'Carga progresiva post-lesión',
                'vertical' => 'entrenamiento',
                'description_short' => 'Volver del 0%. Empezar con 40-50% del peso anterior y subir 5-10% por semana solo si no hay dolor.',
                'description_long' => "Post-lesión (incluso lesiones menores como tendinitis o esguinces grado 1), el músculo se atrofia y la propiocepción se altera. Volver con el peso de antes garantiza recaída.\n\nProtocolo: 1) confirmar alta médica si hubo lesión moderada+, 2) primera semana 40-50% del peso pre-lesión, 3) +5-10% semanal solo si NO hay dolor durante ni después, 4) si reaparece dolor, parar y bajar.",
                'when_to_apply' => 'Intake del cliente menciona lesión activa o reciente (<6 meses). Sustituir ejercicios contraindicados por alternativas.',
                'example_usage' => 'Notas del ejercicio donde aplica: "Por el hombro que te molestaba, en lugar de press militar parado vamos con press sentado en máquina. Arrancamos en 60% de tu peso usual. Subimos cuando lleves 2 semanas sin molestia."',
                'tags' => json_encode(['lesion', 'rehabilitacion', 'prevencion']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'frecuencia_2x_por_grupo',
                'name' => 'Frecuencia 2× por grupo es óptima para hipertrofia',
                'vertical' => 'entrenamiento',
                'description_short' => 'Schoenfeld 2016 meta-análisis: entrenar cada grupo 2x/semana produce 30-40% más ganancias que 1x/semana, igualando volumen total.',
                'description_long' => "El paradigma viejo de 'un día por grupo' (Bro Split) está superado por la evidencia. Distribuir el mismo volumen total en 2 sesiones (ej. 16 series pecho en 2x8 vs 1x16) produce mejores ganancias por mejor calidad de cada serie y mayor estímulo proteico semanal.\n\nEsto NO significa que Body Part Split (1x/sem) sea malo — sirve a clientes con poco tiempo o que prefieren entrenos largos. Pero para hipertrofia óptima: Upper/Lower 4d o PPL 6d permiten 2x frecuencia.\n\nReferencia: Schoenfeld, Ogborn, Krieger 2016 (J Sports Sci).",
                'when_to_apply' => 'Cliente con objetivo hipertrofia + tiempo disponible 4+ días/semana. Especialmente importante para intermedios+ que ya tienen base.',
                'example_usage' => 'Notas del coach: "Tu split toca cada grupo 2x por semana (lunes y jueves). Eso multiplica el estímulo proteico vs entrenarlo 1 sola vez con doble volumen."',
                'tags' => json_encode(['hipertrofia', 'fundamental', 'progresion']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'tempo_controlado_bajada',
                'name' => 'Tempo: 2-3 segundos en la bajada (eccéntrica)',
                'vertical' => 'entrenamiento',
                'description_short' => 'La fase eccéntrica (bajada) genera 2x más estímulo muscular que la concéntrica. Bajar en 2-3s vs caer libre cambia el rendimiento.',
                'description_long' => "La fase eccéntrica del movimiento (la bajada en sentadilla, el descenso en press banca) es donde ocurre el mayor daño muscular controlado y por ende el mayor estímulo hipertrófico. Caer en peso libre desperdicia esa fase.\n\nTempo estándar para hipertrofia: 2-1-2-1 (2s bajada, 1s pausa abajo, 2s subida, 1s pausa arriba).\nPara fuerza: 1-0-X-0 (X = explosivo, sin pausa).\n\nNO significa hacer las reps lentas siempre — significa controlar la bajada deliberadamente. Es lo que diferencia un entreno serio de un entreno sin control.",
                'when_to_apply' => "Todos los clientes, especialmente principiantes (que tienden a 'tirarse' al bajar) e intermedios estancados (mejorar tempo es lever de progreso).",
                'example_usage' => 'Notas: "En cada serie, bajá controlando en 2-3 segundos. Si la última rep ya no podés bajar despacio, la cuenta no sirve — terminá la serie."',
                'tags' => json_encode(['hipertrofia', 'fundamental', 'tecnica']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'mind_muscle_connection_aislados',
                'name' => 'Conexión mente-músculo en ejercicios de aislamiento',
                'vertical' => 'entrenamiento',
                'description_short' => 'En isolations (curl, lateral raise, leg extension), enfocar conscientemente el músculo trabajado mejora activación 20-40%.',
                'description_long' => "Schoenfeld 2018: focus interno (mind-muscle connection) durante isolations aumenta EMG ~20-40% comparado con focus externo (mover el peso). En multi-articulares grandes (sentadilla, press banca, peso muerto) el efecto se invierte: focus externo es mejor.\n\nReglas operativas:\n- Compounds pesados (>80% 1RM): focus externo ('empujar el piso', 'romper la barra')\n- Compounds livianos / técnicos: focus mixto\n- Isolations: focus interno ('siento el bíceps contraerse', 'aprieto el pecho en cada rep')\n\nNo es 'magia mental' — es atención dirigida a la fibra que se quiere trabajar. Cliente que no siente el músculo en isolation está perdiendo 30% del estímulo.",
                'when_to_apply' => 'Cliente en hipertrofia que NO siente el músculo objetivo durante isolations (curl, lateral raise, leg extension). Especialmente principiantes que se enfocan solo en levantar el peso.',
                'example_usage' => "Notas: 'En el curl de bíceps, bajá el peso si hace falta y SENTÍ el bíceps contraerse en cada rep. El peso es secundario — la activación es lo que cuenta acá.'",
                'tags' => json_encode(['hipertrofia', 'tecnica', 'progresion']),
                'evidence_level' => 'alta',
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-81',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'deload_semana_cada_4_6',
                'name' => 'Deload programado cada 4-6 semanas',
                'vertical' => 'entrenamiento',
                'description_short' => 'Semana de descarga (volumen -40-50%, intensidad -10%) cada 4-6 semanas previene overreaching y permite supercompensar.',
                'description_long' => "Acumular volumen + intensidad indefinidamente lleva a overreaching → meseta → overtraining. La solución NO es entrenar más, es planificar 1 semana cada 4-6 con carga reducida:\n\nProtocolo de deload:\n- Volumen: -40 a -50% (ej. 3 series → 2 series)\n- Intensidad: -10% del peso o +1-2 RIR\n- Frecuencia: igual o ligeramente menor\n- Cardio: mantener NEAT, reducir HIIT\n\nResultado: el cuerpo supercompensa, fuerza vuelve mejor, sueño/ánimo mejoran, motivación se renueva.\n\nNo es 'descanso pasivo' — es entrenamiento estratégicamente reducido. Clientes que saltan deloads suelen estancar a las 8-12 semanas.",
                'when_to_apply' => 'Plan de hipertrofia/fuerza/recomposición con >4 semanas. Cliente reporta fatiga acumulada, performance bajando, motivación baja.',
                'example_usage' => "Notas: 'Semana 5 = deload. Misma estructura pero series -40% y peso -10%. NO la saltes aunque te sientas bien — es parte de la progresión.'",
                'tags' => json_encode(['progresion', 'recuperacion', 'fundamental']),
                'evidence_level' => 'alta',
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-81',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ─── NUTRICIÓN (4) ─────────────────────────────────────────────────
            [
                'slug' => 'proteina_primero',
                'name' => 'Proteína primero',
                'vertical' => 'nutricion',
                'description_short' => 'Si no llegás a las calorías del día pero cumpliste tu proteína, el día sigue siendo productivo.',
                'description_long' => "La proteína es el macronutriente más crítico para preservar (y construir) músculo. Distribución típica: 1.8-2.4 g/kg de peso corporal para personas entrenando con peso.\n\nPrioridad operativa: si el día se complicó y solo podés controlar UNA cosa, asegurate de cumplir tu objetivo de proteína. Los carbos y grasas tienen más flexibilidad.",
                'when_to_apply' => 'En todo plan nutricional. Especialmente importante para clientes en déficit (perdida_grasa) o que vienen de dietas muy bajas en proteína.',
                'example_usage' => 'tips_nutricionales: "Si te quedaste corto de calorías pero cumpliste tus 180g de proteína, el día sigue contando. La proteína es la única no-negociable."',
                'tags' => json_encode(['fundamental', 'macros']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'distribucion_de_proteina',
                'name' => 'Distribución de proteína en 4-5 comidas',
                'vertical' => 'nutricion',
                'description_short' => 'Distribuir la proteína en 4-5 comidas con 30-40g cada una maximiza síntesis proteica vs concentrarla en 1-2 comidas grandes.',
                'description_long' => "La síntesis proteica muscular tiene un techo por comida (~0.4 g/kg). Comer 100g de proteína en 1 comida no es 2.5× más anabólico que 40g — el excedente se metaboliza para energía o se almacena.\n\nDistribución óptima: 4-5 comidas con 30-45g de proteína cada una, espaciadas 3-4h. Incluye fuentes variadas: animal completa (huevo, pollo, pescado, lácteos) + vegetal complementaria.",
                'when_to_apply' => 'Al armar el meal plan. Si el cliente prefiere ayuno intermitente, ajustar a 3 comidas más grandes pero no menos.',
                'example_usage' => 'Cada comida del plan tiene su objetivo de proteína específico (ej. desayuno 30g, almuerzo 40g, pre-entreno 25g, cena 40g, snack PM 25g = 160g).',
                'tags' => json_encode(['macros', 'timing']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'hidratacion_minima',
                'name' => 'Hidratación mínima 35 ml/kg/día',
                'vertical' => 'nutricion',
                'description_short' => 'Mínimo 35 ml de agua por kg de peso corporal al día, +500 ml por hora de entrenamiento intenso.',
                'description_long' => "La deshidratación leve (-2% del peso corporal en líquidos) reduce fuerza, resistencia y enfoque cognitivo significativamente. La sed NO es indicador temprano — cuando sentís sed ya estás deshidratado.\n\nCálculo: peso × 0.035 = L base diarios. Más 0.5L por cada hora de entrenamiento. En climas cálidos o altitud, sumar 20-30%.",
                'when_to_apply' => 'En todo plan nutricional. Especialmente para clientes en Colombia/LATAM costeros (clima cálido) o ciudades de altura (Bogotá +2600m).',
                'example_usage' => 'Sección hidratación del JSON: "Tu mínimo diario son 3.2 L de agua (90kg × 35ml). Los días que entrenás, sumá 500ml extra durante la sesión y otros 500ml en la hora siguiente."',
                'tags' => json_encode(['fundamental', 'hidratacion']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'timing_pre_entreno',
                'name' => 'Pre-entreno 60-90 min antes',
                'vertical' => 'nutricion',
                'description_short' => 'Comida pre-entreno con carbo + proteína 60-90 min antes da combustible sin pesadez digestiva.',
                'description_long' => "El pre-entreno ideal es una comida moderada (300-500 kcal) con 30-50g de carbo y 20-30g de proteína, consumida 60-90 min antes del gym. Da glucógeno disponible y aminoácidos circulantes sin causar pesadez.\n\nEjemplos: arroz + pollo + verduras, avena + claras + banano, batata + atún. Evitar grasas altas y fibra excesiva (retrasan digestión).",
                'when_to_apply' => 'Cuando el cliente entrena en horario fijo. Si entrena en ayunas, ajustar (BCAAs o proteína líquida) y mover macros a la primera comida post.',
                'example_usage' => 'Si el cliente entrena 18:00, pre-entreno es 16:30-17:00. Cena fuerte después del entreno (19:30-20:00) con proteína + carbos para recuperación.',
                'tags' => json_encode(['timing', 'rendimiento']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'post_entreno_proteina_carbo',
                'name' => 'Post-entreno: proteína + carbo dentro de 60 min',
                'vertical' => 'nutricion',
                'description_short' => 'La ventana anabólica existe pero es ancha (~3h). Lo importante es reponer proteína + carbo dentro de la primera hora post-entreno.',
                'description_long' => "La ventana anabólica tradicional ('30 min después del entreno') está sobre-vendida — la ventana real es ~3 horas. Pero reponer dentro de la primera hora optimiza:\n\n- Síntesis proteica muscular: 25-40g proteína de alta calidad\n- Reposición de glucógeno: 0.5-1.0 g/kg de carbo en la primera hora\n\nEjemplos: batido whey + banano, yogur griego + miel + granola, sandwich de pollo con pan integral.\n\nSi el entreno termina cerca de una comida normal (cena, almuerzo), esa comida cumple ese rol — no necesitás algo extra.",
                'when_to_apply' => 'Cuando el cliente reporta entrenar y tardar 2-3h en comer después. Especialmente en hipertrofia y recomposición.',
                'example_usage' => "Notas: 'Después del gym (18hs), tu cena (19hs-20hs) ya cuenta como post-entreno. No necesitás batido extra — la cena con proteína + carbo es suficiente.'",
                'tags' => json_encode(['timing', 'macros', 'recuperacion']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'vegetariano_completar_aminoacidos',
                'name' => 'Vegetariano: combinar fuentes para perfil completo',
                'vertical' => 'nutricion',
                'description_short' => 'Las proteínas vegetales son completas si combinás 2 fuentes. Arroz+lenteja, garbanzo+quinoa, trigo+soja.',
                'description_long' => "Cada proteína vegetal individual es 'incompleta' (faltan 1-2 aminoácidos esenciales), pero combinando 2 fuentes el perfil se completa. Las combinaciones clásicas LATAM:\n\n- Arroz + lentejas (clásico colombiano)\n- Garbanzo + quinoa\n- Frijoles + tortilla de maíz\n- Tofu + arroz integral\n\nNO hace falta combinarlas en la MISMA comida — basta con consumirlas a lo largo del día (el pool de aminoácidos del cuerpo se mantiene varias horas).\n\nVeganos estrictos: considerar suplementación con B12, hierro y omega-3 (DHA algal).",
                'when_to_apply' => 'Cliente vegetariano o vegano. Especialmente si entrena con foco hipertrofia.',
                'example_usage' => "Notas: 'Como sos vegetariana, combiná arroz+lenteja en almuerzo y quinoa+garbanzo en cena. NO necesitás que cada comida tenga combo — el cuerpo lo arma a lo largo del día.'",
                'tags' => json_encode(['macros', 'vegetariano', 'adherencia']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'frecuencia_comidas_flexible',
                'name' => '5 comidas no es ley — 3, 4, 5 o 6 son válidas',
                'vertical' => 'nutricion',
                'description_short' => 'El estudio clave (Schoenfeld 2015) confirma: 3-6 comidas dan igual resultado SI los macros totales se cumplen.',
                'description_long' => "El mito del metabolismo acelerado por 5-6 comidas pequeñas está derribado por la literatura (Schoenfeld & Aragon 2018). Lo que importa:\n\n- TOTAL diario de calorías + macros (esto manda)\n- Mínimo 3 comidas con ~30g de proteína cada una (saturar síntesis proteica)\n- Adherencia a la vida real del cliente\n\nClientes que trabajan oficina: 3-4 comidas suelen funcionar mejor (menos preparación). Atletas serios: 5-6 si toleran. Ayuno intermitente 16/8: 2-3 comidas dentro de la ventana.\n\nNO hay 'correcta' — solo la que el cliente puede SOSTENER.",
                'when_to_apply' => 'Cuando el cliente reporta no poder cumplir 5 comidas/día por vida ocupada. O cuando pregunta si tiene que comer cada 3 horas (no, no tiene).',
                'example_usage' => "Notas: 'Si 5 comidas no te encajan, hacé 3 con porciones más grandes. El total de proteína/carbos/grasas es lo que importa — no el número de meals.'",
                'tags' => json_encode(['adherencia', 'realismo', 'macros']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'fibra_25_35g_diaria',
                'name' => 'Fibra 25-35 g/día — anti-saciedad y microbiota',
                'vertical' => 'nutricion',
                'description_short' => 'Adultos LATAM consumen 12-15 g de fibra/día. El target 25-35 g mejora saciedad, glucemia y microbiota intestinal.',
                'description_long' => "La dieta promedio LATAM es pobre en fibra (12-15 g/día vs 25-35 g recomendados). Consecuencias del déficit:\n- Saciedad baja → overeating crónico subclínico\n- Picos de glucosa post-comida\n- Microbiota desbalanceada → inflamación de bajo grado\n- Estreñimiento (común en clientes en déficit)\n\nFuentes prácticas (1 porción ≈ 5-8 g):\n- 1 taza brócoli/coliflor cocido (~5 g)\n- 1 manzana con piel (~4 g)\n- 1/2 taza frijoles/lentejas cocidos (~7 g)\n- 1 taza avena (~4 g)\n- 1 taza fresas/frambuesas (~8 g)\n\nNo apurar (subir +5 g por semana) para evitar gases/distensión.",
                'when_to_apply' => 'Plan de nutrición en perdida_grasa o recomposicion. Cliente reporta hambre/saciedad pobre, estreñimiento, o se obsesiona contando calorías sin tener fibra cubierta.',
                'example_usage' => "Notas: 'Tu target diario de fibra es 25-30 g. Llegás sumando 2-3 porciones de verdura + 1 fruta + 1 ración de legumbres o avena. Subí gradualmente si arrancás bajo.'",
                'tags' => json_encode(['adherencia', 'macros', 'saciedad', 'progresion']),
                'evidence_level' => 'alta',
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-67',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'post_entreno_30g_proteina',
                'name' => 'Post-entreno: 30 g proteína de alta calidad en <2 h',
                'vertical' => 'nutricion',
                'description_short' => 'Saturar MPS (síntesis proteica muscular) con 25-40 g proteína completa. Ventana real: 2-4 h, no 30 min.',
                'description_long' => "El mito de la 'ventana anabólica de 30 min' fue refinado por la literatura (Schoenfeld 2013, Aragon & Schoenfeld 2018). La realidad:\n\n- La ventana es 2-4 h post-entreno (no 30 min)\n- El factor crítico: 25-40 g proteína completa con 2-3 g leucina\n- Si comiste 1-2 h ANTES de entrenar, la urgencia post baja\n\nFuentes prácticas para 30 g:\n- 1 scoop whey (25 g) + 1 huevo (6 g)\n- 130 g pechuga pollo cocida\n- 5 huevos enteros\n- 1 lata atún (≈25 g) + queso fresco\n\nNo es excusa para no comer post — solo es flexibilidad temporal. Adherencia > timing perfecto.",
                'when_to_apply' => "Cliente que entrena ≥3x/sem y pregunta cuándo comer post. O cliente obsesivo con el 'shake en 30 min'. Educar la ventana real.",
                'example_usage' => "Tip: 'Después de entrenar, apuntá a 25-30 g proteína completa dentro de las 2 horas. Si comiste 1-2 h antes de entrenar, no urgente. Si entrenaste en ayuno, sí comé apenas puedas.'",
                'tags' => json_encode(['macros', 'timing', 'recuperacion', 'progresion']),
                'evidence_level' => 'alta',
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-67',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'alcohol_kcal_invisible',
                'name' => 'Alcohol: 7 kcal/g y bloquea síntesis proteica',
                'vertical' => 'nutricion',
                'description_short' => '1 copa de vino = 130 kcal. Una noche social puede sumar 800+ kcal "invisibles" que tumban la semana en déficit.',
                'description_long' => "El alcohol aporta 7 kcal/g (entre carbs y grasa) y NO se almacena — el cuerpo lo prioriza para metabolizar, deteniendo oxidación de grasas hasta procesarlo todo.\n\nEfectos relevantes:\n- 1 copa vino = 130 kcal · 1 cerveza = 150 kcal · 1 trago licor = 100 kcal\n- Suprime síntesis proteica muscular ~30% por 24-48 h\n- Empeora calidad de sueño (menos REM, más despertares)\n- Día siguiente: hambre por desregulación de leptina\n\nRegla operativa: hasta 2 unidades/semana de vino tinto sin afectar mucho. >3 unidades/sem en déficit = adelgaza más lento. Cliente reporta no avanzar y omite contar viernes/sábado de tragos — ahí está el bug.",
                'when_to_apply' => 'Cliente en perdida_grasa que reporta no progresar a pesar de "comer perfecto" entre semana. O cliente social que va a eventos frecuentes.',
                'example_usage' => "Notas: 'Si vas a tomar el sábado, calculá: 2 copas vino = ~260 kcal. Restalas del almuerzo o reduciselas durante la semana. NO ignores esa caloría — manda.'",
                'tags' => json_encode(['macros', 'adherencia', 'progresion']),
                'evidence_level' => 'alta',
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-82',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'sodio_no_es_enemigo',
                'name' => 'Sodio no es el enemigo — atletas necesitan 3-5 g/día',
                'vertical' => 'nutricion',
                'description_short' => 'Dietas low-sodium agresivas en atletas activos causan calambres, baja performance, mareos. Target: 3-5 g sodio/día (8-12 g sal).',
                'description_long' => "La fobia al sodio viene de estudios en hipertensos sedentarios. Para personas activas y entrenadas, el sodio es electrolito CRÍTICO:\n- Función muscular (contracción)\n- Hidratación celular (sin sodio el agua no se retiene)\n- Performance aerobic + anaerobic\n\nAtleta deportista promedio: 3-5 g sodio/día (≈8-12 g sal de mesa).\nEntreno intenso/calor: +1-2 g extras durante/post.\n\nLos signos de SODIO BAJO son comunes y confundidos con 'falta de hidratación':\n- Calambres frecuentes\n- Fatiga vespertina\n- Dolor de cabeza post-entreno\n- Mareo al levantarse\n\nEXCEPCIÓN: cliente con hipertensión diagnosticada → seguir indicación médica.",
                'when_to_apply' => "Cliente activo que reporta calambres, mareos, fatiga inexplicada. O dieta muy 'limpia' con cero sodio agregado.",
                'example_usage' => "Notas: 'Si te dan calambres o te sentís flojo, sumá sal a las comidas. Atleta sano necesita 3-5 g sodio/día. Si tenés HTA diagnosticada decímelo y ajustamos.'",
                'tags' => json_encode(['macros', 'recuperacion', 'realismo']),
                'evidence_level' => 'alta',
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-82',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ─── SUPLEMENTACIÓN (5) ────────────────────────────────────────────
            [
                'slug' => 'creatina_basal',
                'name' => 'Creatina monohidrato 5g/día (basal)',
                'vertical' => 'suplementacion',
                'description_short' => 'El suplemento más estudiado y efectivo que existe. 5g diarios constantes — sin fases de carga ni descansos.',
                'description_long' => "Creatina monohidrato (no HCl, no Kre-Alkalyn — el monohidrato es el que tiene 100+ estudios) aumenta fuerza ~5-10% y volumen muscular ~1-2 kg en intermedios+ tras 4-8 semanas.\n\nProtocolo simple: 5g todos los días (con o sin entreno, con o sin comida). Las fases de carga (20g × 5 días) son innecesarias — el efecto es el mismo al mes 1 con 5g/día. No requiere descansos cíclicos.",
                'when_to_apply' => 'Todo plan de suplementación. Excepción: clientes con problemas renales preexistentes (consultar médico).',
                'example_usage' => 'Lista de suplementos del plan: "Creatina Monohidrato 5g — Cualquier momento del día, todos los días incluyendo descansos. Suplemento basal, no opcional."',
                'tags' => json_encode(['basal', 'evidencia_alta', 'fundamental']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'whey_no_es_obligatoria',
                'name' => 'Whey es opcional, no obligatoria',
                'vertical' => 'suplementacion',
                'description_short' => 'Whey ayuda si no llegás a tu target proteico con alimentos enteros. Si llegás, podés ahorrarte la plata.',
                'description_long' => "La whey es UNA forma cómoda de cubrir gaps de proteína — no un macronutriente mágico. Cliente que llega tranquilamente a 2g/kg con pollo+huevos+lácteos NO necesita whey.\n\nUseful cuando: cliente con vida ocupada que no come bien al mediodía, post-entreno cuando no hay tiempo de cocinar, viaje. NO útil: marketing que dice 'whey = más músculo'.",
                'when_to_apply' => 'Considerar whey solo si el cliente reporta no llegar a target proteico con alimentos. Si llega, sugerir invertir en mejor calidad de alimentos enteros.',
                'example_usage' => 'Notas del coach: "Whey en este stack es opcional. Si llegás a tus 150g de proteína con comida real, no es necesaria. La metí para casos en que tu agenda no permita 5 comidas."',
                'tags' => json_encode(['macros', 'realismo', 'adherencia']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'cafeina_timing_no_dosis',
                'name' => 'Cafeína: timing importa más que dosis',
                'vertical' => 'suplementacion',
                'description_short' => 'Cafeína 30-60 min pre-entreno mejora performance 3-7%. Más dosis NO mejora resultado — y empeora sueño.',
                'description_long' => "Dosis efectiva: 3-6 mg/kg, 30-60 min antes del entreno. Por encima de 6 mg/kg los efectos secundarios (ansiedad, taquicardia, mal sueño) anulan el beneficio.\n\nRegla: NO consumir cafeína 8h antes de dormir (vida media ~5h en adultos). Si entrenás 18hs, café 17:00 es OK. Si entrenás 20hs, mejor té verde o sin cafeína post-17:00.\n\nTolerancia: ciclar 2-3 semanas + 1 semana sin para mantener sensibilidad.",
                'when_to_apply' => 'Clientes que ya consumen café/té y reportan necesitar dosis altas. O quienes entrenan tarde y reportan mal sueño.',
                'example_usage' => 'Notas: "Si tu entreno es a las 18hs, tomá café o pre-workout entre 17:00-17:30. NADA de cafeína después de las 17:00 si te cuesta dormir. La dosis óptima no es la máxima — es la mínima que rinde."',
                'tags' => json_encode(['timing', 'rendimiento']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'no_apilar_estimulantes',
                'name' => 'Nunca apilar 2 estimulantes el mismo día',
                'vertical' => 'suplementacion',
                'description_short' => 'Pre-workout + café + termogénico = riesgo cardiovascular real (taquicardia, presión alta, ansiedad). Elegir UNO.',
                'description_long' => "Cliente típico: toma 1 café por la mañana + pre-workout 17hs + termogénico al mediodía. Total: 400+ mg cafeína + sinefrina + yohimbina = arritmia + presión arterial peligrosa.\n\nRegla operativa: si el cliente toma pre-workout, NO suplementar termogénico. Si toma 2-3 cafés al día, NO agregar pre-workout con cafeína (usar versión sin caf).\n\nSeñales de alarma: temblor en manos, palpitaciones, dolor de cabeza vespertino, insomnio inexplicado.",
                'when_to_apply' => 'Cliente reporta tomar pre-workout + café (varios) + termogénico simultáneamente. Educar sobre suma de estimulantes y posibles efectos cardio.',
                'example_usage' => 'Notas del coach: "Si tomás este pre-workout, NO sumes termogénico ni más de 1 café al día. El total de cafeína diaria no debe superar 400mg para vos."',
                'tags' => json_encode(['fundamental', 'prevencion', 'seguridad']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'suplemento_completa_no_sustituye',
                'name' => 'Los suplementos complementan, NO sustituyen',
                'vertical' => 'suplementacion',
                'description_short' => 'Ningún suplemento compensa mal sueño, dieta basura o entrenamiento mal hecho. Son la cereza, no el pastel.',
                'description_long' => "Marketing fitness vende suplementos como atajos — la realidad es que el 90% del resultado viene de los pilares básicos: entrenamiento progresivo, dieta consistente, sueño adecuado.\n\nUn cliente con stack premium ($300 USD/mes) pero que duerme 5hs y come fast food NO va a progresar. Un cliente sin nada de suplementos pero con los pilares cumplidos va a progresar.\n\nOrden de prioridad: 1) sueño, 2) entreno, 3) comida, 4) hidratación, 5) suplementos (último 10% optimización).",
                'when_to_apply' => "Cuando el cliente pregunta '¿qué suplemento debería tomar?' antes de tener fundamentos sólidos. Educar antes de vender.",
                'example_usage' => 'Notas del coach: "Antes de gastar en suplementos avanzados, revisemos tu sueño y tu adherencia al plan nutricional. Si esos 2 están sólidos, los suplementos rinden mucho más."',
                'tags' => json_encode(['fundamental', 'adherencia', 'realismo']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'magnesio_glicinato_sueno',
                'name' => 'Magnesio bisglicinato 300-400 mg pre-sueño',
                'vertical' => 'suplementacion',
                'description_short' => 'Magnesio en forma bisglicinato (no óxido) 30-60 min antes de dormir mejora latencia y profundidad de sueño en deficitarios.',
                'description_long' => "El déficit de magnesio es común en LATAM por suelos pobres y consumo limitado de hojas verdes oscuras / semillas. Síntomas: calambres nocturnos, sueño superficial, ansiedad de fondo.\n\nForma: bisglicinato (alta biodisponibilidad, no laxante). Evitar óxido (mala absorción, diarrea). Dosis: 300-400 mg de magnesio elemental 30-60 min antes de dormir.\n\nNo es reemplazo de higiene de sueño (oscuridad, frío, no pantallas) — es un agregado modesto. Evidencia decente pero no espectacular.",
                'when_to_apply' => 'Cliente reporta calambres nocturnos, sueño fragmentado, ansiedad leve, o atletas con alto sudor (entreno >5x/sem).',
                'example_usage' => 'Notas del coach: "Probá magnesio bisglicinato 300 mg después de la cena. Si en 2 semanas notás mejor sueño, mantenelo. Si no cambia nada, suspendé — no todos lo necesitan."',
                'tags' => json_encode(['recuperacion', 'sueno', 'adherencia']),
                'evidence_level' => 'moderada',
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-64',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'cafeina_timing_no_8h_pre_sueno',
                'name' => 'Cafeína: corte 8 horas antes de dormir',
                'vertical' => 'suplementacion',
                'description_short' => 'Vida media cafeína ≈5h. Última dosis ≥8h antes de dormir o el sueño profundo se reduce aunque te duermas igual.',
                'description_long' => "El error típico: 'me duermo bien con café tarde, no me afecta'. La gente NO percibe la pérdida de sueño profundo (slow-wave sleep) — solo nota fatiga vaga al día siguiente.\n\nVida media de la cafeína: 5h en metabolizadores rápidos, 8-9h en lentos. Última dosis a las 14-15hs si te dormís a las 22-23hs. Si entrenás a las 18hs, usar pre-workout SIN cafeína o con dosis baja (<100 mg).\n\nMarcadores de exceso: dificultad para conciliar, despertares en madrugada, ansiedad/temblor manos, dependencia diaria de >3 cafés.",
                'when_to_apply' => 'Cliente toma café/pre-workout tarde y reporta sueño superficial, fatiga crónica, ansiedad. También al diseñar pre-workout para entrenos vespertinos.',
                'example_usage' => 'Notas del coach: "Última cafeína a las 14:00 hs como máximo. Si entrenás a las 18-19hs, pre-workout sin cafeína (beta-alanina + citrulina) o un café chico antes de las 14hs."',
                'tags' => json_encode(['fundamental', 'recuperacion', 'sueno', 'progresion']),
                'evidence_level' => 'alta',
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-64',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'vitamina_d3_dosis_efectiva',
                'name' => 'Vitamina D3: 2000-5000 IU/día con grasa, ideal con K2',
                'vertical' => 'suplementacion',
                'description_short' => 'Deficiencia de D3 es endémica en LATAM urbano. Suplementar 2000-5000 IU/día con grasa mejora performance, ánimo y recovery.',
                'description_long' => "La vitamina D3 es de las pocas con evidencia para suplementar incluso a no-deficitarios sub-óptimos. En LATAM oficinista típico (8h indoor + protector solar) los niveles séricos están entre 15-25 ng/mL — sub-óptimos (target: 40-60 ng/mL).\n\nDosis efectivas:\n- Mantenimiento: 2000-4000 IU/día con grasa (mejor absorción)\n- Reposición rápida (deficit confirmado <20): 5000 IU/día x 8 sem, luego mantenimiento\n- Sinergia: combinar con K2 (MK-7 100-200 mcg) para direccionar calcio al hueso, no a arterias\n\nMomento: con la comida más grasa del día (desayuno/almuerzo, no cena).\n\nMidalo: pedir 25-OH-D si hay duda. Es uno de los pocos test costo-efectivos.",
                'when_to_apply' => 'TODO plan de suplementación en LATAM urbano. Especialmente cliente que reporta fatiga crónica, baja inmunidad, mood bajo invernal, lesiones articulares recurrentes.',
                'example_usage' => 'Notas: "Suplementa D3 5000 IU/día con desayuno. Te recomiendo pedir 25-OH-D vitamin D en próximo chequeo para ajustar dosis."',
                'tags' => json_encode(['fundamental', 'recuperacion', 'salud_general']),
                'evidence_level' => 'alta',
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-83',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'cafeina_dosis_efectiva_pre',
                'name' => 'Cafeína pre-entreno: 3-6 mg/kg, 30-45 min antes',
                'vertical' => 'suplementacion',
                'description_short' => 'Dosis efectiva ergogénica: 3-6 mg/kg de peso corporal, 30-45 min antes de entreno. Tope 400 mg/día total.',
                'description_long' => "Cafeína es uno de los pocos suplementos con evidencia robusta para performance: +2-7% en fuerza máxima, resistencia, agilidad mental. Pero la dosis importa:\n\n- 1-2 mg/kg: efecto modesto, principalmente alerta\n- 3-6 mg/kg: ZONA EFECTIVA ERGOGÉNICA (atleta 70 kg = 210-420 mg)\n- >6 mg/kg: meseta + side effects (ansiedad, temblor, gastric)\n\nTiming: pico plasmático a 30-45 min. Tomar 30 min antes del warmup.\n\nLímite diario total (incluyendo café del día): 400 mg para evitar acumulación + insomnio.\n\nNo desarrolla tolerancia para fuerza/potencia (sí para alerta) — no necesita ciclar.",
                'when_to_apply' => 'Cliente entrenado que quiere bumping de performance. Atleta deportivo. Evitar en cliente con ansiedad, HTA no controlada, embarazo.',
                'example_usage' => 'Notas: "Cafeína 3 mg/kg (para vos: 210 mg = 1 espresso doble + 1 chico) 30 min antes de entrenar. Si tomás más café en el día, restalo del total para no pasar 400 mg."',
                'tags' => json_encode(['progresion', 'realismo', 'performance'])
                ,
                'evidence_level' => 'muy_alta',
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-83',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ─── CICLO MENSTRUAL (3) ────────────────────────────────────────────
            [
                'slug' => 'ciclo_no_es_excusa_es_dato',
                'name' => 'El ciclo es info, no excusa',
                'vertical' => 'ciclo',
                'description_short' => "Conocer en qué fase estás permite ajustar carga inteligentemente. No es para 'explicar' días flojos.",
                'description_long' => "El ciclo modula recuperación, fuerza y respuesta hormonal — pero la diferencia entre fases es del 5-10% en performance, no del 50%. Mujeres entrenadas hacen PRs durante menstruación.\n\nUsá el tracking como info para ajustar volumen/intensidad cuando aplica (lútea tardía: +200 kcal, bajar volumen 10%). NO uses la fase para justificar días sin entrenar — eso no es plan, es excusa.\n\nLa fase NO determina tu performance — tu dedicación sí.",
                'when_to_apply' => "Cliente femenina con tracking activo. Especialmente cuando reporta que ciertas semanas 'rinde menos' sistemáticamente.",
                'example_usage' => 'Notas: "La fase lútea tardía pide más comfort food y menos volumen — perfecto, ajustá. Pero esos PRs los vamos a hacer en fase folicular, no son imposibles en otras fases."',
                'tags' => json_encode(['fundamental', 'realismo', 'progresion']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'lutea_tardia_sumar_calorias',
                'name' => "Lútea tardía: sumar 100-200 kcal (no es 'romper la dieta')",
                'vertical' => 'ciclo',
                'description_short' => 'En la semana antes de la menstruación, el cuerpo pide más calorías. Sumalas planificado, no por antojo.',
                'description_long' => "Durante la fase lútea tardía (1 semana antes del sangrado), la temperatura corporal sube ~0.5°C y el gasto basal aumenta 5-10%. Eso son 100-200 kcal extra diarias que el cuerpo pide.\n\nIgnorar esa señal lleva a antojos descontrolados (binge) que rompen la adherencia. Sumarla planificada (más arroz, más fruta, más grasa buena) la mantiene en macros.\n\nNO es 'darse permiso' — es matemática de gasto vs ingesta.",
                'when_to_apply' => 'Cliente en déficit calórico que reporta antojos fuertes en una semana específica del mes. Cross-check con tracking de ciclo.',
                'example_usage' => 'Notas: "Días 22-28 de tu ciclo, sumá 1 porción extra de carbohidrato o fruta al almuerzo. Tu cuerpo lo pide y es legítimo. NO es romper el plan — es leerlo bien."',
                'tags' => json_encode(['macros', 'recuperacion', 'adherencia']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'anticonceptivos_son_dato_no_obstaculo',
                'name' => 'Anticonceptivos hormonales: dato, no obstáculo',
                'vertical' => 'ciclo',
                'description_short' => 'Con COC/IUD hormonal la variabilidad del ciclo natural está suprimida. Igual hay ajustes finos según efectos secundarios.',
                'description_long' => "Mujeres con anticonceptivos hormonales (píldora combinada, IUD hormonal, implante) tienen ciclo menos variable que el natural — pero NO totalmente plano. Efectos secundarios típicos modulan performance:\n\n- Retención líquidos: peso fluctúa ±1-2 kg sin cambio de composición\n- Cefalea cíclica: ajustar carga ese día\n- Cambio de mood: contemplar en notas_coach\n\nLa fase placebo (4-7 días sin hormonas) puede mimic los efectos del ciclo natural a escala reducida.",
                'when_to_apply' => 'Cliente con anticonceptivos hormonales. Suele requerir menos ajustes pero NO ninguno.',
                'example_usage' => 'Notas: "Con tu IUD hormonal el ciclo no fluctúa tanto. Pero los días de placebo (si aplican) pueden traer cefalea — ajustá carga el día que sientas eso, sin culpa."',
                'tags' => json_encode(['adherencia', 'recuperacion']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'folicular_ventana_anabolica',
                'name' => 'Fase folicular: ventana óptima para PRs y volumen alto',
                'vertical' => 'ciclo',
                'description_short' => 'Días 1-14 del ciclo (folicular): estrógeno asciende → mayor tolerancia a volumen, mejor recuperación, ventana óptima para PRs de fuerza.',
                'description_long' => "Durante la fase folicular (especialmente días 7-14), el estrógeno está en ascenso. Esto:\n\n- Aumenta la tolerancia al volumen entrenable (~10-15% más capacidad)\n- Mejora la recuperación entre sesiones (menor inflamación basal)\n- Favorece adaptaciones de fuerza (mayor sensibilidad andrógena)\n\nESTRATEGIA: planificar las semanas de mayor intensidad/volumen en folicular tardía. Si vas a meter un PR de sentadilla, planificalo aquí. La fase lútea tardía es para deload o consolidación.\n\nNO significa entrenar 'fácil' fuera de folicular — significa que el cuerpo tolera estímulos más agresivos en esta ventana.",
                'when_to_apply' => 'Cliente femenina con tracking activo + ciclo regular (NO en anticonceptivos hormonales). Especialmente útil planificando bloques de fuerza/hipertrofia.',
                'example_usage' => 'Notas: "Los días 7-14 de tu ciclo son tu ventana fuerte. Si tenés un PR pendiente o un día de alta intensidad, programalo ahí. Días 22-28 bajá volumen 10-15%."',
                'tags' => json_encode(['progresion', 'hipertrofia', 'fuerza']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'sintomas_pms_red_flags',
                'name' => 'Síntomas PMS severos: red flag — derivar a ginecólogo',
                'vertical' => 'ciclo',
                'description_short' => 'PMS leve es normal. Pero dismenorrea severa, sangrado anormal o cambios de mood incapacitantes requieren evaluación médica.',
                'description_long' => "El PMS leve (1-2 días de calambres, fatiga, antojo de carbos) es fisiológico. El TDPM (Trastorno Disfórico Premenstrual) NO — afecta funcionalidad y requiere tratamiento.\n\nRED FLAGS para derivar a ginecólogo:\n- Sangrado >7 días o muy abundante (cambio de toalla c/2h)\n- Dolor que requiere analgésicos fuertes o falta al trabajo\n- Cambios de mood incapacitantes (depresión severa, ansiedad >7 días)\n- Ciclos irregulares prolongados (>40 días sin sangrado)\n- Sangrado entre menstruaciones\n\nEL COACH NO TRATA — deriva. Suplementar magnesio + vitamina B6 ayuda al PMS leve. Para lo severo, ginecólogo SIEMPRE.\n\nLa amenorrea hipotalámica (sin menstruación por déficit calórico) es OTRA cosa — requiere PAUSAR el déficit y reevaluar.",
                'when_to_apply' => 'Cliente reporta síntomas PMS severos, ciclos irregulares o ausencia prolongada. NUNCA dar consejos médicos — siempre derivar.',
                'example_usage' => 'Notas: "Esos síntomas (sangrado abundante 8+ días + dolor incapacitante) son red flag médico. Hacé cita con ginecólogo antes de seguir con el plan. Mientras tanto bajamos la intensidad."',
                'tags' => json_encode(['fundamental', 'seguridad', 'prevencion']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'lutea_extra_carbos_recovery',
                'name' => 'Fase lútea tardía: +100-200 kcal carbos + recovery extra',
                'vertical' => 'ciclo',
                'description_short' => 'Días 21-28 (pre-menstrual): metabolismo basal sube ~5%, antojo de carbos no es debilidad — es fisiología. Sumar 100-200 kcal carbos.',
                'description_long' => "Durante la fase lútea tardía (después de ovulación, antes de menstruación), el cuerpo:\n- Aumenta metabolismo basal ~3-5% (~75-150 kcal extras quemadas)\n- Aumenta sensibilidad a insulina (carbos se usan mejor)\n- Aumenta percepción de fatiga + irritabilidad por bajada de progesterona\n- Aumenta antojo de carbohidratos/dulces (mecanismo serotoninérgico real, NO falta de fuerza de voluntad)\n\nProtocolo inteligente:\n- Sumar 100-200 kcal extras (mejor en carbos complejos: avena, arroz, fruta)\n- Reducir intensidad 10% si el cliente lo siente\n- Priorizar sueño + magnesio\n- NO restringir agresivo — empeora síntomas + adherencia\n\nESTAS son las ventanas para hacer ajustes inteligentes — no para abandonar el plan.",
                'when_to_apply' => 'Cliente femenina con tracking activo en fase lútea tardía. Especialmente si reporta antojo intenso, fatiga, mood bajo días previos a menstruación.',
                'example_usage' => "Notas: 'Días 21-28 sumá 1 fruta y 1 porción de arroz/avena extra. El antojo de dulce es fisiológico, no falta de voluntad — cubrilo con carbos complejos antes que te lleve a binge.'",
                'tags' => json_encode(['adherencia', 'macros', 'progresion', 'realismo']),
                'evidence_level' => 'moderada',
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-84',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'perimenopausia_red_flags',
                'name' => 'Perimenopausia: red flags + ajustes inteligentes',
                'vertical' => 'ciclo',
                'description_short' => 'Mujeres 40-55: ciclos irregulares + sofocos + insomnio no son "vejez". Son perimenopausia tratable. Derivar + ajustar entreno.',
                'description_long' => "La perimenopausia (3-10 años antes de la menopausia, típicamente 40-55) NO es 'envejecer y aguantar'. Es transición hormonal con síntomas tratables:\n\nSÍNTOMAS comunes:\n- Ciclos irregulares (acortando o alargando)\n- Sofocos (hot flashes) diurnos/nocturnos\n- Insomnio + sueño fragmentado\n- Ánimo lábil (similar a PMS pero crónico)\n- Pérdida de masa muscular acelerada (sin entreno de fuerza)\n- Aumento de grasa abdominal (cambio composición)\n\nQUÉ HACE EL COACH:\n- Priorizar ENTRENO DE FUERZA (preserva masa magra y densidad ósea)\n- Sumar D3 + magnesio + omega-3\n- Sueño como prioridad #1\n- NO restringir agresivo (cortisol ya está alterado)\n- Derivar a ginecólogo si síntomas severos — TRH (terapia de reemplazo hormonal) tiene buena evidencia en candidatas apropiadas\n\nNO ES TABÚ. Es etapa de vida que requiere coaching distinto.",
                'when_to_apply' => 'Cliente femenina 40-55 con tracking. Síntomas perimenopáusicos. NO improvisar — derivar a ginecólogo y ajustar plan.',
                'example_usage' => 'Notas: "Lo que describís (ciclos irregulares + sofocos + insomnio) suena a perimenopausia. Te recomiendo cita con ginecóloga para evaluar opciones (TRH es muy efectiva en muchos casos). Mientras, priorizamos fuerza + sueño + suplementos clave."',
                'tags' => json_encode(['fundamental', 'seguridad', 'realismo']),
                'evidence_level' => 'alta',
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-84',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ─── HÁBITOS (3) ────────────────────────────────────────────────────
            [
                'slug' => 'sueno_es_anabolico',
                'name' => 'Sueño es anabólico',
                'vertical' => 'habitos',
                'description_short' => 'Dormir 7-9h consistentes vale más que cualquier suplemento. La GH y la recuperación muscular pico ocurren en sueño profundo.',
                'description_long' => "Las horas de sueño son cuando ocurre la mayoría del trabajo de recuperación muscular: pico de hormona de crecimiento (GH), reparación de fibras, consolidación neurológica del patrón motor entrenado.\n\nDormir 5-6h consistentes anula la mitad de las ganancias de entrenamiento — está documentado en múltiples estudios. Prioridad: horario fijo (mismo ±30 min entre semana y fin de semana), oscuridad total, temperatura fresca, sin pantallas 1h antes.",
                'when_to_apply' => 'En todo plan, especialmente cuando el cliente reporta progreso lento sin causa clara o fatiga sostenida.',
                'example_usage' => 'Pilar del plan de hábitos: "Sueño es no-negociable. 7.5h promedio semanal. Si trabajás de noche, hablalo con el coach y armamos un plan ajustado."',
                'tags' => json_encode(['fundamental', 'recuperacion']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'registro_es_clave',
                'name' => 'Registro es clave (anotás o no progresás)',
                'vertical' => 'habitos',
                'description_short' => 'Anotar peso, reps y RIR de cada serie es lo que permite progresión consciente vs entrenar de memoria.',
                'description_long' => "Sin registro, no hay sobrecarga progresiva real — solo recuerdo selectivo de la última sesión. El cliente que anota peso, reps y RIR sabe exactamente cuándo subir carga, cuándo está estancado, y cuándo necesita deload.\n\nMétodos: app WellCore (preferido), libreta, notas en celular. Lo importante es CONSISTENCIA. Registrar 80% del tiempo es 100× mejor que registrar 100% del primer mes y nada después.",
                'when_to_apply' => 'En la primera sesión / intake. Si el cliente entrena hace tiempo pero no registra, mencionar como cambio importante.',
                'example_usage' => 'Tip del plan: "Anotá peso, reps y RIR de cada serie en la app WellCore después de cada ejercicio. No al final del día — en el momento."',
                'tags' => json_encode(['fundamental', 'progresion']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'adherencia_sobre_perfeccion',
                'name' => 'Adherencia 80% sostenida > perfección 100% efímera',
                'vertical' => 'habitos',
                'description_short' => 'Cumplir el plan al 80% durante 12 semanas vence a cumplirlo al 100% durante 2 y abandonar.',
                'description_long' => "El error clásico: plan perfecto en papel, ejecutado al 100% por 2 semanas, abandonado por agotamiento o vida real. Resultado neto: cero ganancias y frustración.\n\nDiseñar planes para 80% de adherencia: días flexibles, opciones de comida realistas para la vida del cliente, margen para imprevistos. El 20% de imperfección es feature, no bug.",
                'when_to_apply' => 'Cuando el cliente reporta culpa por días saltados o comidas off-plan. Recordar el principio antes de que abandone por sentir que ya falló.',
                'example_usage' => 'En notas_coach iniciales: "Vas a tener semanas perfectas y semanas raras. Si cumplís 80% sostenido, ganamos. No me importa la semana perfecta seguida de tres ausentes — me importa la semana de 4/5 sostenida 12 semanas."',
                'tags' => json_encode(['fundamental', 'adherencia', 'realismo']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'postura_escritorio_pausas',
                'name' => 'Postura escritorio: pausas activas cada 60-90 min',
                'vertical' => 'habitos',
                'description_short' => '8h sentado al día genera tensión cervical y debilidad postural. Pausas de 2 min cada 60-90 min revierten parte del daño.',
                'description_long' => "Estar sentado 8+ horas activa el patrón de 'síndrome cruzado superior' (hombros adelantados, cuello en flexión, espalda media débil). Esto NO se compensa con 1 hora de gym.\n\nPausas efectivas (2 min cada 60-90 min de trabajo):\n- 10 face-pulls con banda elástica (escapulares retractores)\n- 10 thoracic extensions sobre silla\n- 30 seg estiramiento de psoas (zancada estática)\n\nLevantar la pantalla a altura de ojos previene flexión cervical crónica. Si no podés, comprar elevador de monitor (15 USD).",
                'when_to_apply' => 'Clientes con trabajo de oficina o estudio prolongado. Especialmente quienes reportan dolor cervical o lumbar crónico bajo.',
                'example_usage' => 'Tip del plan: "Cada hora de trabajo, levantate 2 min: 10 face-pulls con banda + estirar psoas. No es opcional si pasás 8+ hs sentado."',
                'tags' => json_encode(['fundamental', 'prevencion_lesiones', 'postura']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'gestion_estres_cortisol',
                'name' => 'Gestión de estrés: 10 min/día reduce cortisol crónico',
                'vertical' => 'habitos',
                'description_short' => 'Cortisol crónico bloquea recomposición. 10 min/día de respiración consciente bajan cortisol salival ~20%.',
                'description_long' => "Estrés crónico (trabajo + entreno + vida) eleva cortisol basal. Cortisol alto sostenido bloquea: pérdida de grasa abdominal, recuperación muscular, calidad del sueño.\n\nMétodos validados (10 min/día):\n- Respiración 4-7-8 (4 inhalar, 7 sostener, 8 exhalar) × 4 rondas\n- Meditación guiada (apps: Calm, Insight Timer)\n- Caminata silenciosa sin teléfono\n- Journaling 3 cosas del día\n\nNO es 'wellness para venderte cursos' — es respuesta vagal medible. Hasta 70% de clientes en estancamiento prolongado mejoran al sumar este hábito.",
                'when_to_apply' => 'Cliente que reporta no progresar a pesar de plan + nutrición perfectos. O quienes describen estrés crónico (trabajo intenso, problemas familiares, falta de tiempo).',
                'example_usage' => 'Notas: "Sumá 10 minutos al día de algo que te baje el sistema nervioso — respiración 4-7-8, caminata sin teléfono, lo que prefieras. Esto NO es relajación opcional, es parte del plan."',
                'tags' => json_encode(['recuperacion', 'fundamental', 'adherencia']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'neat_diario_pasos',
                'name' => 'NEAT: 7-10k pasos diarios + actividad no-entreno',
                'vertical' => 'habitos',
                'description_short' => 'NEAT (Non-Exercise Activity Thermogenesis) suma 200-500 kcal/día. Más impacto en composición que el cardio formal.',
                'description_long' => "NEAT es el gasto calórico de TODO lo que NO es entreno formal: pasos, escaleras, gestos, postura. En personas sedentarias representa ~200 kcal/día; en personas activas, hasta 1000 kcal/día.\n\nObjetivos prácticos:\n- 7,000 pasos: mínimo viable para no-sedentario\n- 10,000 pasos: target sostenible para clientes promedio\n- 12,000+ pasos: clientes en déficit calórico agresivo\n\nSubir escaleras en lugar de ascensor, caminar al supermercado, levantarse del escritorio — todo cuenta. Smartwatch o app de pasos hace tracking pasivo.\n\nLECCIÓN CLAVE: 30 min de cardio formal NO compensan 8h sentado.",
                'when_to_apply' => 'TODO plan. Especialmente en perdida_grasa donde el déficit calórico real depende del NEAT, no solo del entreno.',
                'example_usage' => 'Tip del plan: "Apuntá a 10,000 pasos diarios. Bajate del bus 2 paradas antes, subí escaleras, andá al kiosco caminando. Esto vale más para tu composición que 1 hora extra de cardio."',
                'tags' => json_encode(['adherencia', 'macros', 'progresion']),
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'digital_detox_bedroom',
                'name' => 'Detox digital en el dormitorio (90 min pre-sueño)',
                'vertical' => 'habitos',
                'description_short' => 'Luz azul + dopamina de redes destruye latencia del sueño. Sin pantallas 90 min antes de dormir, dormitorio sin TV.',
                'description_long' => "El uso de pantallas 90 min antes de dormir hace 2 cosas medibles:\n1. Luz azul suprime melatonina ~50% durante la exposición.\n2. Notificaciones + scroll generan picos de dopamina que activan el simpático (modo alerta) cuando deberías ir al parasimpático (modo descanso).\n\nProtocolo realista:\n- Charger del celular FUERA del dormitorio (despertador analógico)\n- Si necesitás leer, libro físico o e-reader e-ink (no tablet)\n- TV fuera del cuarto si es posible (mínimo apagada antes de cama, sin dormirse mirándola)\n- Modo no-molestar 22:00-7:00\n\nNo es prohibición religiosa — es higiene. Mejorás latencia + profundidad de sueño sin gastar un peso.",
                'when_to_apply' => 'Cliente reporta dificultad para conciliar el sueño, despertar cansado, o uso compulsivo del celular en cama. Sumar antes de proponer suplementos.',
                'example_usage' => "Notas: 'A partir de hoy, el celular se queda en la sala después de las 22:00 hs. Comprá un despertador analógico de $20. En 2 semanas notás la diferencia en cómo te despertás.'",
                'tags' => json_encode(['fundamental', 'sueno', 'recuperacion', 'adherencia']),
                'evidence_level' => 'alta',
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-70',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'tracking_semanal_no_diario',
                'name' => 'Tracking semanal, NO diario (peso + medidas)',
                'vertical' => 'habitos',
                'description_short' => 'Pesarse diario rompe la cabeza por ruido de hidratación/digestión. Promedio semanal a misma hora es la señal real.',
                'description_long' => "El peso corporal varía ±1-2 kg día a día por agua, glucógeno, comida pendiente de digestión, sodio, ciclo menstrual. Pesarse diario y reaccionar emocionalmente:\n- Te lleva a abandonar el plan tras un mal viernes\n- Genera ansiedad innecesaria\n- No correlaciona con grasa real (la grasa cambia a ritmo de 0.3-0.7 kg/semana máximo)\n\nProtocolo recomendado:\n- Pesar 1-2x/semana, mismo día(s), mismo horario (matutino, post-baño, en ayunas)\n- Promediar 4 semanas para ver tendencia\n- Medidas (cintura, cadera, brazos) cada 4 semanas — cuentan más que el peso\n- Foto de espejo mensual misma luz/pose\n\nLA REGLA: si subiste 0.5 kg en 2 días pero comiste igual, NO es grasa — es agua.",
                'when_to_apply' => 'Plan en perdida_grasa o recomposicion. Cliente obsesivo con la balanza o que abandonó planes anteriores por desmotivación de pesajes diarios.',
                'example_usage' => "Notas: 'Te peso los martes y viernes en ayunas. Los demás días NO subas a la balanza. Las medidas y la foto valen más que el número diario.'",
                'tags' => json_encode(['adherencia', 'realismo', 'tracking', 'progresion']),
                'evidence_level' => 'alta',
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-70',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'luz_solar_matutina_15min',
                'name' => 'Luz solar matutina 10-15 min en la primera hora',
                'vertical' => 'habitos',
                'description_short' => 'Exposición a luz solar 10-15 min en los primeros 60 min post-despertar regula cortisol matutino y melatonina nocturna.',
                'description_long' => "Tu reloj circadiano sigue la luz, no el reloj de pulsera. Recibir luz solar directa (no a través de ventana) en los primeros 60 min después de despertar:\n\n- Eleva cortisol matutino → energía + alerta sostenida\n- Suprime melatonina restante → menos somnolencia diurna\n- Calibra ritmo circadiano → mejor melatonina nocturna 14-16h después\n- Mejora ánimo (especialmente en invierno LATAM sur)\n\nProtocolo realista:\n- 10-15 min directos al sol (sin lentes oscuros)\n- Día nublado: extender a 20-30 min\n- Si imposible salir: lámpara 10,000 lux 20 min (caro pero efectivo)\n- Café afuera vale más que café leyendo el celular en cama\n\nGratis. Sin pastilla. Más efectivo que melatonina suplementada para la mayoría.",
                'when_to_apply' => 'Cliente con problemas de sueño, fatiga matutina, mood bajo invernal, trabajo remoto que casi no sale. TODO plan en realidad.',
                'example_usage' => "Notas: 'Antes de mirar el celular en la mañana, salí al balcón/jardín/patio 10 min con tu café. Sin lentes. Esto regula tu sueño esa noche.'",
                'tags' => json_encode(['fundamental', 'sueno', 'recuperacion', 'adherencia']),
                'evidence_level' => 'alta',
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-85',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'cocinar_propio_3x_semana',
                'name' => 'Cocinar propio mínimo 3x/semana (anti-procesados ultra)',
                'vertical' => 'habitos',
                'description_short' => 'Cocinar tu propia comida es el control de calidad más subestimado en composición corporal. Mínimo 3 batch-cooks semanales.',
                'description_long' => "Los procesados ultra (NOVA 4) tienen:\n- Densidad calórica artificialmente alta (food engineering for hyperpalatability)\n- Baja saciedad relativa al kcal\n- Aceites de mala calidad (palmister, soja refinada)\n- Aditivos que correlacionan con inflamación de bajo grado\n\nCocinar propio NO requiere ser chef:\n- 1 batch cook el domingo (90 min) = 4-5 comidas listas\n- Recetas simples: pollo plancha + arroz + verdura. Lentejas + arroz. Atún + ensalada.\n- Congelar porciones\n\nObjetivo MÍNIMO: 3 días/semana 100% casero. El resto, lo mejor que se pueda.\n\nClientes que solo comen delivery/pre-hecho rara vez progresan SOSTENIDAMENTE sin importar cuánto se midan macros.",
                'when_to_apply' => 'Cliente que come >50% fuera o procesado. Cliente en estancamiento prolongado a pesar de tracking aparente. Cliente con poco presupuesto.',
                'example_usage' => "Notas: 'Tarea de la semana: 1 batch cook el domingo. Algo simple: 600 g pollo plancha + 3 tazas arroz + bandeja de verduras al horno. Te alcanza para 4 comidas. Esto manda más que cualquier suplemento.'",
                'tags' => json_encode(['fundamental', 'adherencia', 'macros', 'realismo']),
                'evidence_level' => 'alta',
                'status' => 'active',
                'created_by' => 'seed-mvp-sprint-85',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        // Normalizar: garantizar que todas las rows tengan las mismas keys
        // (evidence_level se agregó en Sprint 56 — rows previos no lo declaran)
        // La columna es NOT NULL ENUM con default 'alta', así que ese es el fallback razonable.
        foreach ($rows as &$row) {
            $row['evidence_level'] = $row['evidence_level'] ?? 'alta';
        }
        unset($row);

        DB::connection('kb')
            ->table('principles')
            ->upsert($rows, ['slug'], [
                'name', 'vertical', 'description_short', 'description_long',
                'when_to_apply', 'example_usage', 'tags', 'evidence_level',
                'status', 'created_by', 'updated_at',
            ]);

        $this->command?->info('Seeded ' . count($rows) . ' principles.');
    }
}
