/**
 * Presets de celebraciones — define categoría + colores + defaults por tipo.
 */
export const PRESETS = {
    workout: {
        category: 'workout',
        accentColor: 'red',
        heroClass: 'wc-hero-accent',
        borderClass: 'border-wc-accent/30',
        subtitleColor: 'text-emerald-400',
        titleIcon: 'wc-barbell',
        subtitleIcon: 'wc-check',
        soundKey: 'pr-hit',
        hapticPattern: 'success',
        confettiPreset: 'burst',
        cta: 'Ver detalle',
        ctaIcon: 'wc-arrow-right',
    },
    photos: {
        category: 'photos',
        accentColor: 'emerald',
        heroClass: 'wc-hero-emerald',
        borderClass: 'border-emerald-500/30',
        subtitleColor: 'text-emerald-400',
        titleIcon: 'wc-camera',
        subtitleIcon: 'wc-photo',
        soundKey: 'photo-snap',
        hapticPattern: 'light',
        confettiPreset: 'rain',
        cta: 'Ver línea de tiempo',
        ctaIcon: 'wc-arrow-right',
    },
    medal: {
        category: 'medal',
        accentColor: 'amber',
        heroClass: 'wc-hero-amber',
        borderClass: 'border-amber-500/30',
        subtitleColor: 'text-amber-400',
        titleIcon: 'wc-medal-hex',
        subtitleIcon: 'wc-sparkles',
        soundKey: 'achievement',
        hapticPattern: 'achievement',
        confettiPreset: 'cannon',
        cta: 'Ver logros',
        ctaIcon: 'wc-arrow-right',
        lottieFile: '/lottie/trophy-unlock.json',
    },
    'level-up': {
        category: 'level-up',
        accentColor: 'violet',
        heroClass: 'wc-hero-violet',
        borderClass: 'border-violet-500/30',
        subtitleColor: 'text-violet-400',
        titleIcon: 'wc-level-ring',
        subtitleIcon: 'wc-xp-bolt',
        soundKey: 'level-up',
        hapticPattern: 'levelUp',
        confettiPreset: 'wc-branded',
        cta: 'Continuar',
        ctaIcon: 'wc-arrow-right',
        lottieFile: '/lottie/level-ring.json',
    },
    checkin: {
        category: 'checkin',
        accentColor: 'blue',
        heroClass: 'wc-hero-blue',
        borderClass: 'border-blue-500/30',
        subtitleColor: 'text-blue-400',
        titleIcon: 'wc-coach',
        subtitleIcon: 'wc-chat-bubble',
        soundKey: 'checkmark',
        hapticPattern: 'success',
        confettiPreset: 'burst',
        cta: 'Ir al dashboard',
        ctaIcon: 'wc-arrow-right',
    },
    habits: {
        category: 'habits',
        accentColor: 'emerald',
        heroClass: 'wc-hero-emerald',
        borderClass: 'border-emerald-500/30',
        subtitleColor: 'text-emerald-400',
        titleIcon: 'wc-check',
        subtitleIcon: 'wc-check',
        soundKey: 'streak-fire',
        hapticPattern: 'success',
        confettiPreset: 'rain',
        cta: 'Seguir mañana',
        ctaIcon: 'wc-arrow-right',
    },
    metrics: {
        category: 'metrics',
        accentColor: 'emerald',
        heroClass: 'wc-hero-emerald',
        borderClass: 'border-emerald-500/30',
        subtitleColor: 'text-emerald-400',
        titleIcon: 'wc-check',
        subtitleIcon: 'wc-chart-line-up',
        soundKey: 'checkmark',
        hapticPattern: 'light',
        confettiPreset: 'burst',
        cta: 'Ver gráfico completo',
        ctaIcon: 'wc-arrow-right',
    },
    'rise-workout': {
        category: 'workout',
        accentColor: 'red',
        heroClass: 'wc-hero-accent',
        borderClass: 'border-wc-accent/30',
        subtitleColor: 'text-emerald-400',
        titleIcon: 'wc-xp-bolt',
        subtitleIcon: 'wc-xp-bolt',
        soundKey: 'pr-hit',
        hapticPattern: 'success',
        confettiPreset: 'burst',
        cta: 'Siguiente día',
        ctaIcon: 'wc-arrow-right',
    },
    'coach-feedback': {
        category: 'coach',
        accentColor: 'blue',
        heroClass: 'wc-hero-blue',
        borderClass: 'border-blue-500/30',
        subtitleColor: 'text-blue-400',
        titleIcon: 'wc-coach',
        subtitleIcon: 'wc-heart',
        soundKey: 'soft-ding',
        hapticPattern: 'light',
        confettiPreset: null,
        cta: 'Volver',
        ctaIcon: 'wc-arrow-left',
    },
    'onboarding-coach': {
        category: 'coach',
        accentColor: 'blue',
        heroClass: 'wc-hero-blue',
        borderClass: 'border-blue-500/30',
        subtitleColor: 'text-blue-400',
        titleIcon: 'wc-coach',
        subtitleIcon: 'wc-check',
        soundKey: 'achievement',
        hapticPattern: 'achievement',
        confettiPreset: 'burst',
        cta: 'Al dashboard',
        ctaIcon: 'wc-home',
    },
    welcome: {
        category: 'welcome',
        accentColor: 'violet',
        heroClass: 'wc-hero-violet',
        borderClass: 'border-violet-500/30',
        subtitleColor: 'text-violet-400',
        titleIcon: 'wc-logo',
        subtitleIcon: 'wc-rocket',
        soundKey: 'level-up',
        hapticPattern: 'achievement',
        confettiPreset: 'wc-branded',
        cta: '¡Comienza!',
        ctaIcon: 'wc-arrow-right',
    },
    payment: {
        category: 'payment',
        accentColor: 'amber',
        heroClass: 'wc-hero-amber',
        borderClass: 'border-amber-500/30',
        subtitleColor: 'text-amber-400',
        titleIcon: 'wc-coin',
        subtitleIcon: 'wc-check',
        soundKey: 'coin-jingle',
        hapticPattern: 'success',
        confettiPreset: 'rain',
        cta: 'Ir a mi cuenta',
        ctaIcon: 'wc-arrow-right',
    },
};

export function getPreset(name) {
    return PRESETS[name] || PRESETS.workout;
}
